# Generated by Django 6.0.7 on 2026-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_account_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
